repository_type: pipeline

nf_core_version: 3.3.2

lint: {}

template:
  org: nf-core
  name: mdallpipeline
  description: Full pipeline to run MD-ALL from Nanopore cDNA or dRNA fastq files
  author: msagniez
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
